version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: loyalty_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - loyalty_network

volumes:
  mongo:

networks:
  loyalty_network: